# disable plugins we don't / can't support
disabled_plugins = ["aufs", "btrfs", "zfs"]

# import any additional config files written by kind, and any user written
# config files (/etc/containerd/user-config/*.toml)
imports = ["/kind/containerd/*.toml", "/etc/containerd/user/*.toml"]

# set default runtime handler to v2, which has a per-pod shim
[plugins."io.containerd.grpc.v1.cri".containerd]
  default_runtime_name="runc"
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
  runtime_type = "io.containerd.runc.v2"

# Setup kubernetes e2e test fixed-name ("test-handler") for runtime class tests
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.test-handler]
  runtime_type = "io.containerd.runc.v2"
