name: json-yaml-validate 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  json-yaml-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@v1.2.0
        with:
          yaml_exclude_regex: "(/static/examples/.*(usage|metallb-config).yaml|.*invalid-yaml)"
