name: Publish to Winget

on:
  release:
    types: [released]

permissions: {}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Setup Komac
        run: |
          curl -fSsL -o komac.jar https://github.com/russellbanks/Komac/releases/download/v1.11.0/Komac-1.11.0-all.jar
          echo '1c26bb7bee6228ad095fe67d10ed254363099b3395f809bd6d95a3f72b2740fc komac.jar' | sha256sum --check --status -
      
      - name: Update and submit manifest
        run: |
          $JAVA_HOME_17_X64/bin/java -jar komac.jar update \
            --id Kubernetes.kind \
            --version $(echo '${{ github.event.release.name }}' | sed 's/^v//') \
            --urls https://github.com/kubernetes-sigs/kind/releases/download/${{ github.event.release.name }}/kind-windows-amd64
            --token ${{ secrets.WINGET_TOKEN }}
            --submit
